name: Testando

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
   testes:
    runs-on: ubuntu-latest
   
    steps:
      -name: primeiro
       run: echo "aaaaaaaaaaaaaaaaaaaaaaaaa" 
      -name: segundo
       run: echo "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
