name: Testando

on:
  push:
    branch: [ master ]
  pull_request:
    branch: [ master ]


jobs:
   tests:
    runs-on: ubuntu-lastest
   
    steps:
      -name: primeiro
       run: echo "aaaaaaaaaaaaaaaaaaaaaaaaa" 
      -name: segundo
       run: echo "bbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
